version: "2"
services:
  rucio:
    image: rucio/rucio-dev
    ports:
      - "443:443"
    links:
      - mysql:postgres
      - graphite:graphite
    volumes:
      - ../../../tools:/opt/rucio/tools
      - ../../../bin:/opt/rucio/bin
      - ../../../lib:/opt/rucio/lib
  mysql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
