version: "2"
services:
  rucio:
    image: rucio/rucio-dev
    ports:
      - "443:443"
    links:
      - mysql:mysql
      - graphite:graphite
    volumes:
      - ../../../tools:/opt/rucio/tools
      - ../../../bin:/opt/rucio/bin
      - ../../../lib:/opt/rucio/lib
  mysql:
    image: mysql/mysql-server:latest
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=latin1']
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
